const data = [
  { name: "Potato", satiety: 7 },
  { name: "Rice", satiety: 4 },
  { name: "Pasta", satiety: 4 },
  { name: "Bread", satiety: 3 },
  { name: "Broccoli", satiety: 5 },
  { name: "Apple", satiety: 5 },
  { name: "Banana", satiety: 6 },
  { name: "Strawberries", satiety: 5 },
  { name: "Lettuce", satiety: 2 },
  { name: "Cucumber", satiety: 2 },
  { name: "Tomato", satiety: 4 },
  { name: "Carrot", satiety: 4 },
  { name: "Chicken", satiety: 7 },
  { name: "Beef", satiety: 7 },
  { name: "Salmon", satiety: 7 },
  { name: "Tuna", satiety: 7 },
  { name: "Eggs", satiety: 6 },
  { name: "Cheese", satiety: 6 },
  { name: "Spinach", satiety: 4 },
  { name: "Mushrooms", satiety: 5 },
  { name: "Oats", satiety: 5 },
  { name: "Corn", satiety: 4 },
  { name: "Peas", satiety: 5 },
  { name: "Lentils", satiety: 7 },
  { name: "Beans", satiety: 7 },
  { name: "Almonds", satiety: 6 },
  { name: "Walnuts", satiety: 6 },
  { name: "Peanuts", satiety: 6 },
  { name: "Milk", satiety: 4 },
  { name: "Yogurt", satiety: 4 },
  { name: "Olives", satiety: 5 },
  { name: "Avocado", satiety: 7 },
  { name: "Blueberries", satiety: 4 },
  { name: "Oranges", satiety: 5 },
  { name: "Pineapple", satiety: 5 },
  { name: "Grapes", satiety: 4 },
  { name: "Pears", satiety: 5 },
  { name: "Peaches", satiety: 5 },
  { name: "Plums", satiety: 5 },
  { name: "Cherries", satiety: 4 },
  { name: "Watermelon", satiety: 4 },
  { name: "Kiwi", satiety: 4 },
  { name: "Pomegranate", satiety: 5 },
  { name: "Raspberries", satiety: 5 },
  { name: "Blackberries", satiety: 5 },
  { name: "Cantaloupe", satiety: 4 },
  { name: "Bell Pepper", satiety: 4 },
  { name: "Garlic", satiety: 3 },
  { name: "Onion", satiety: 3 },
  { name: "Cabbage", satiety: 4 },
  { name: "Cauliflower", satiety: 4 },
  { name: "Radish", satiety: 3 },
  { name: "Cottage Cheese", satiety: 6 },
  { name: "Brown Rice", satiety: 5 },
  { name: "Quinoa", satiety: 6 },
  { name: "Buckwheat", satiety: 6 },
  { name: "Sweet Potato", satiety: 7 },
  { name: "Pork", satiety: 7 },
  { name: "Soybean", satiety: 7 },
  { name: "Tofu", satiety: 6 },
  { name: "Chickpeas", satiety: 7 },
  { name: "Lamb", satiety: 7 },
  { name: "Turkey", satiety: 7 },
  { name: "Shrimp", satiety: 6 },
  { name: "Cod", satiety: 6 },
  { name: "Pasta, whole grain", satiety: 5 },
  { name: "Mango", satiety: 5 },
  { name: "Grapefruit", satiety: 5 },
  { name: "Papaya", satiety: 4 },
  { name: "Artichoke", satiety: 5 },
  { name: "Bok Choy", satiety: 3 },
  { name: "Brussel Sprouts", satiety: 5 },
  { name: "Zucchini", satiety: 4 },
  { name: "Asparagus", satiety: 4 },
  { name: "Feta Cheese", satiety: 5 },
  { name: "Sardines", satiety: 6 },
  { name: "Oysters", satiety: 6 },
  { name: "Clams", satiety: 7 },
  { name: "Mussels", satiety: 6 },
  { name: "Eggplant", satiety: 4 },
  { name: "Chia Seeds", satiety: 7 },
  { name: "Pumpkin Seeds", satiety: 6 },
  { name: "Sunflower Seeds", satiety: 6 },
  { name: "Flax Seeds", satiety: 6 },
  { name: "Pine Nuts", satiety: 6 },
  { name: "Pistachios", satiety: 6 },
  { name: "Cashews", satiety: 6 },
  { name: "Hazelnuts", satiety: 6 },
  { name: "Pecans", satiety: 6 },
  { name: "Brazil Nuts", satiety: 6 },
  { name: "Macadamia Nuts", satiety: 6 },
  { name: "Hazelnuts", satiety: 6 },
  { name: "Guava", satiety: 5 },
  { name: "Cantaloupe", satiety: 4 },
  { name: "Pumpkin", satiety: 5 },
  { name: "Squash", satiety: 4 },
  { name: "Alfalfa Sprouts", satiety: 3 },
  { name: "Kale", satiety: 5 },
  { name: "Swiss Chard", satiety: 5 },
  { name: "Romaine Lettuce", satiety: 3 },
];

export { data };
